spring:
  application:
    name: app  # 애플리케이션 이름 (로그 등에서 표시됨)

  datasource:
    url: jdbc:h2:mem:testdb  # H2 메모리 DB URL (개발용)
    driver-class-name: org.h2.Driver
    username: sa             # H2 기본 사용자
    password:                # 비밀번호 없음

  h2:
    console:
      enabled: true          # 웹에서 H2 콘솔 접속 허용
      path: /h2-console      # 기본 접속 경로

  jpa:
    open-in-view: false      # 트랜잭션 범위를 뷰 렌더링까지 열지 않음 (성능 및 지연 쿼리 방지)
    hibernate:
      ddl-auto: update       # 애플리케이션 실행 시 테이블 자동 생성/수정
    show-sql: true           # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true     # SQL 로그 보기 좋게 정렬

jwt:
  secret: my-very-secret-key-jjyoon-1234567890123456
  expiration: 3600000

server:
  port: 8080  # 서버 포트
